/* Pakistan Policy Quest - content library (datasets, methods, scenes, 21 designs).
   Edit this file to add themes, designs, or update dataset years. */
"use strict";
/* ================= DATASET VAULT (real details; verify latest releases) ================= */
var DATA={
 pslm_d:{name:"PSLM \u2014 District Level",yrs:"7 rounds: 2004-05 \u2192 2019-20",
  vars:"Enrollment & literacy, child immunization & diarrhoea, pre/post-natal care, water-sanitation-hygiene, housing, assets, ICT; 2019-20 adds disability & migration modules. ~80,000 households, district-representative.",
  access:"Free microdata (Stata/SPSS) via the PBS microdata portal after a short registration/indent.",
  limit:"Repeated cross-sections (no household panel); questionnaire drift across waves; new-district splits require a careful district crosswalk.",
  aff:{education:3,health:2,gender:2,poverty:2,climate:1,conflict:2,governance:1,labor:1},
  peek:[{t:"Section C: education roster (enrollment, grade, reason out of school)",tags:{theme:{education:2}}},
        {t:"Section D/E: immunization card & child illness",tags:{theme:{health:2}}},
        {t:"Migration module (2019-20): who moved, from where, why",tags:{theme:{labor:1,climate:1,conflict:1}}}]},
 hies:{name:"HIES / PSLM Provincial",yrs:"2004-05 \u2192 2018-19; 9th round 2024-25 (first digital, ~33k HH)",
  vars:"Item-level consumption & expenditure, income by source, plus the social module (education, health, WASH, FIES food insecurity). Basis of official consumption poverty.",
  access:"PBS microdata portal; 2024-25 social & economic reports published \u2014 check portal for the microdata release.",
  limit:"Provincial (not district) representativeness; consumption recall error; long gap between 2018-19 and 2024-25 spans COVID, floods and inflation shocks.",
  aff:{poverty:3,health:2,labor:2,education:1,gender:1,climate:1},
  peek:[{t:"Consumption aggregate & poverty line construction",tags:{theme:{poverty:2}}},
        {t:"Health expenditure lines (out-of-pocket spending)",tags:{theme:{health:2}}},
        {t:"Income by source: wages, remittances, farm",tags:{theme:{labor:2}}}]},
 lfs:{name:"Labour Force Survey (LFS)",yrs:"Long series; 2020-21 round expanded to ~100k HH (district-level estimates)",
  vars:"Employment status, hours, wages, informality, occupation & industry codes (PSCO/PSIC), unemployment, migration reasons, 10+ population.",
  access:"PBS microdata portal, free.",
  limit:"Cross-sections; female work chronically under-reported (probe questions help); wage data only for employees.",
  aff:{labor:3,gender:2,poverty:1,climate:1,conflict:1},
  peek:[{t:"Female labour force participation & reasons for inactivity",tags:{theme:{gender:2,labor:1}}},
        {t:"Informality: no contract, no social security",tags:{theme:{labor:2}}},
        {t:"Wages by occupation & province",tags:{theme:{labor:2}}}]},
 pdhs:{name:"Pakistan DHS (PDHS)",yrs:"1990-91, 2006-07, 2012-13, 2017-18 (+ Maternal Mortality Survey 2019)",
  vars:"Fertility, contraception, child anthropometrics (stunting/wasting), immunization, women's empowerment & decision-making, domestic-violence module (2012-13, 2017-18), GPS cluster coordinates on request.",
  access:"Free at dhsprogram.com after a 1-page project registration.",
  limit:"DV module is a sub-sample with strict ethics protocols; GPS clusters displaced up to 5 km (10 km rural); latest wave now dated.",
  aff:{gender:3,health:3,poverty:1,education:1},
  peek:[{t:"Women's empowerment & decision-making module",tags:{theme:{gender:2}}},
        {t:"Child anthropometrics: HAZ, WHZ, stunting flags",tags:{theme:{health:2}}},
        {t:"Domestic-violence module (ethics-protected)",tags:{theme:{gender:2}}}]},
 mics:{name:"Provincial MICS (UNICEF)",yrs:"Punjab 2017-18 \u00B7 Sindh 2018-19 \u00B7 KP 2019 \u00B7 Balochistan 2019-20",
  vars:"District-representative child & women indicators: early childhood development (ECDI), foundational learning, child discipline, water-quality testing.",
  access:"mics.unicef.org surveys catalogue, free.",
  limit:"Different fieldwork years across provinces complicate pooling; cross-sectional.",
  aff:{health:2,education:2,gender:2,poverty:1},
  peek:[{t:"Foundational learning skills (reading & numeracy, ages 7-14)",tags:{theme:{education:2}}},
        {t:"Water quality: E. coli testing at source & glass",tags:{theme:{health:1,climate:1}}},
        {t:"Child discipline & early development index",tags:{theme:{gender:1,health:1}}}]},
 aser:{name:"ASER Pakistan",yrs:"Roughly annual since 2010 (rural; some urban rounds)",
  vars:"Child-level reading (Urdu/English) and arithmetic tests, enrollment incl. out-of-school children, school facility observations, household assets.",
  access:"Open downloads at aserpakistan.org.",
  limit:"Citizen-led measurement; rural focus; village sampling means care with weights.",
  aff:{education:3,gender:1,climate:1,conflict:1},
  peek:[{t:"Learning outcomes by grade, gender, district",tags:{theme:{education:2}}},
        {t:"Out-of-school children & reasons",tags:{theme:{education:1,gender:1}}},
        {t:"School facility observations (toilets, boundary wall)",tags:{theme:{education:1,governance:1}}}]},
 census:{name:"Population & Housing Census",yrs:"1998, 2017, 2023 (first digital census)",
  vars:"Population by age/sex, literacy, housing, at block/tehsil/district aggregates; essential denominators and long-difference outcomes.",
  access:"Published tables on PBS; microdata not public \u2014 use aggregates.",
  limit:"Long inter-censal gaps; aggregate-only for most users.",
  aff:{poverty:1,labor:1,education:1,governance:1,climate:1},
  peek:[{t:"District literacy & sex ratios 1998\u21922023",tags:{theme:{education:1,gender:1}}},
        {t:"Urbanization & housing stock changes",tags:{theme:{labor:1,climate:1}}},
        {t:"Tehsil population growth (denominators!)",tags:{data:{admin:1}}}]},
 nser:{name:"BISP / NSER Registry",yrs:"PMT scorecard census 2010-11; dynamic re-survey ~2021",
  vars:"Household poverty scores (PMT) with a hard eligibility cutoff for Kafaalat cash transfers, Waseela-e-Taleem education stipends, Nashonuma nutrition top-ups \u2014 a textbook regression-discontinuity setup.",
  access:"Data-sharing agreement with BISP (allow 2-4 months); published OPM evaluation waves are a fallback.",
  limit:"Access negotiation; must test PMT-score manipulation (McCrary density) near the cutoff.",
  aff:{poverty:3,gender:2,education:2,health:1},
  peek:[{t:"PMT score distribution around the eligibility cutoff",tags:{causal:{quasi:2},data:{admin:1}}},
        {t:"Program links: Kafaalat, Waseela-e-Taleem, Nashonuma",tags:{theme:{poverty:1,education:1}}},
        {t:"Woman-of-household as designated payee",tags:{theme:{gender:2}}}]},
 panel:{name:"Household Panels",yrs:"IFPRI Rural Household Panel 2012/2013/2014 \u00B7 PIDE PPHS 2001/2004/2010",
  vars:"Same rural households tracked over rounds (Punjab, Sindh, KP): incomes, shocks, assets, education, migration \u2014 rare true panels for Pakistan.",
  access:"IFPRI Dataverse (free); PPHS via PIDE.",
  limit:"Data now dated; attrition between rounds must be modeled.",
  aff:{poverty:2,labor:2,climate:2,education:1},
  peek:[{t:"Shock module: floods, illness, price shocks",tags:{theme:{climate:2}}},
        {t:"Round-to-round income & asset dynamics",tags:{theme:{poverty:2}}},
        {t:"Attrition patterns (who left the panel?)",tags:{causal:{quasi:1}}}]},
 admin:{name:"Administrative Records",yrs:"Varies by department",
  vars:"Punjab school census & PMIU monthly monitoring, PEC grade 5/8 exam records, DHIS2 health facility data, Sehat Sahulat enrollment & claims, LRMIS land-record mutations, police FIRs & court case flow.",
  access:"Official letters, RTI requests, or MoUs; supervisor/institution backing helps enormously.",
  limit:"Coverage and consistency vary; expect cleaning pain and access delays \u2014 budget for both.",
  aff:{governance:3,education:2,health:2,labor:1,conflict:1},
  peek:[{t:"Sehat Sahulat claims by district & month",tags:{theme:{health:2},data:{admin:1}}},
        {t:"LRMIS mutation (transfer) volumes by tehsil",tags:{theme:{governance:2},data:{admin:1}}},
        {t:"Court case filing & disposal registers",tags:{theme:{governance:2},data:{admin:1}}}]},
 geo:{name:"Conflict & Geospatial Layers",yrs:"GTD to ~2021 \u00B7 PIPS annual \u00B7 CHIRPS 1981\u2013 \u00B7 MODIS/UNOSAT 2022 floods \u00B7 VIIRS nightlights",
  vars:"Geocoded terrorism incidents (GTD, PIPS, ACLED), daily rainfall grids (CHIRPS), flood inundation extents, night-time lights as a local-activity proxy.",
  access:"All open downloads; merge to districts in Stata/R/Python via shapefiles.",
  limit:"Incident data have reporting bias; nightlights are a proxy, not a welfare measure.",
  aff:{conflict:3,climate:3,governance:1,labor:1},
  peek:[{t:"GTD incidents mapped to districts by year",tags:{theme:{conflict:2},data:{geo:1}}},
        {t:"CHIRPS rainfall anomalies by district-season",tags:{theme:{climate:2},data:{geo:1}}},
        {t:"2022 flood extent polygons over union councils",tags:{theme:{climate:2},data:{geo:1}}}]}
};

/* ================= METHODS ================= */
var METH={
 did:{label:"Difference-in-Differences",short:"DiD",
  blurb:"Compare changes over time in places touched by a policy against places that were not, netting out fixed differences and common shocks.",
  assum:["Parallel trends: absent the policy, treated and comparison units would have moved together.","No anticipation, and no contaminating policies hitting only one group.","Stable composition (migration does not reshuffle who is measured where)."],
  robust:["Event-study plot of leads & lags \u2014 flat pre-trends are your first exhibit.","Placebo outcomes that the policy should NOT move.","Alternative comparison groups; triple-difference where a within-unit untreated group exists.","Randomization/permutation inference when treated clusters are few."],
  pros:["Transparent and defensible with the right pre-period data","Works with repeated cross-sections like PSLM"],
  cons:["Lives or dies on the parallel-trends story","Few treated clusters can wreck inference"],
  refs:["Callaway & Sant'Anna (2021), Journal of Econometrics","Goodman-Bacon (2021), Journal of Econometrics"]},
 esdid:{label:"Staggered Rollout / Event Study",short:"Staggered DiD",
  blurb:"When a program arrives in different districts at different times, exploit the rollout with modern estimators (Callaway\u2013Sant'Anna, Sun\u2013Abraham) that avoid the biases of naive two-way fixed effects.",
  assum:["Parallel trends conditional on covariates for each adoption cohort.","No anticipation before local launch.","Rollout timing not driven by outcome trends (test it!)."],
  robust:["Compare CS/SA estimates against naive TWFE \u2014 report both.","Event-study leads for each cohort; Goodman-Bacon decomposition.","Predict rollout timing with observables \u2014 show it is not chasing trends.","Never-treated vs not-yet-treated comparison sets."],
  pros:["Rollouts are everywhere in Pakistan (Sehat Sahulat, LRMIS, e-courts)","Dynamic effects traced over time"],
  cons:["Needs credible rollout-timing story","Data hungry: several pre & post periods"],
  refs:["Callaway & Sant'Anna (2021)","Sun & Abraham (2021), Journal of Econometrics","de Chaisemartin & D'Haultf\u0153uille (2020), AER"]},
 rdd:{label:"Regression Discontinuity",short:"RDD",
  blurb:"Households just above and just below a hard eligibility cutoff (like the NSER PMT score) are near-identical \u2014 the jump at the threshold is the causal effect for that local population.",
  assum:["No precise manipulation of the running variable at the cutoff.","All other determinants of the outcome vary smoothly through the threshold.","The cutoff actually binds (check first-stage take-up for fuzzy designs)."],
  robust:["McCrary/Cattaneo density test for bunching at the cutoff.","Covariate smoothness plots; placebo cutoffs.","Bandwidth & polynomial sensitivity (rdrobust defaults, then vary).","Donut RDD excluding observations closest to the cutoff."],
  pros:["Identification most committees find instantly credible","BISP's PMT cutoff is a nationally important, ready-made design"],
  cons:["Effect is local to the cutoff population","Usually requires administrative score data (access time)"],
  refs:["Cattaneo, Idrobo & Titiunik (2020), CUP element","Lee & Lemieux (2010), JEL"]},
 iv:{label:"Instrumental Variables",short:"IV",
  blurb:"Use a shock that moves your treatment but plausibly affects the outcome only through it \u2014 e.g., rainfall anomalies shifting farm income.",
  assum:["Relevance: strong first stage (report F, weak-IV robust CIs).","Exclusion: the instrument touches the outcome ONLY via treatment \u2014 argue it, do not assume it.","Monotonicity for LATE interpretation."],
  robust:["First-stage strength & Anderson-Rubin confidence sets.","Placebo reduced forms in samples the mechanism should not touch.","Alternative instrument constructions; overidentification only with real second instruments.","State clearly WHOSE effect (compliers) you estimate."],
  pros:["Can rescue questions with no policy experiment","Weather & distance shifters are freely available"],
  cons:["Exclusion restrictions in development settings are fragile \u2014 rainfall moves many things","Referees attack IVs first"],
  refs:["Angrist & Pischke, Mostly Harmless Econometrics","Andrews, Stock & Sun (2019), Annual Review"]},
 rct:{label:"Field Experiment (RCT)",short:"RCT",
  blurb:"Randomize an intervention across individuals, schools, or villages with an implementing partner \u2014 the cleanest identification, and the heaviest logistics.",
  assum:["Successful randomization (show balance).","Compliance measured; spillovers designed for or measured.","Attrition low and non-differential \u2014 or bounded."],
  robust:["Pre-register a pre-analysis plan (AEA registry).","Balance table; Lee bounds for attrition.","Randomization inference; multiple-testing adjustment across outcomes.","Monitor implementation fidelity in the field."],
  pros:["Gold-standard identification","Builds real partner relationships and field skills"],
  cons:["IRB + budget + partner + time \u2014 heavy for a Master's clock","Small samples limit power; plan the MDE honestly"],
  refs:["Duflo, Glennerster & Kremer (2007), Handbook chapter","Glennerster & Takavarasha, Running Randomized Evaluations"]},
 panel:{label:"Honest Descriptive Panel + Event Studies",short:"Descriptive+",
  blurb:"When no clean experiment exists, build the best district panel you can, document robust patterns, and use event studies around large discrete shocks \u2014 with the causal claims dialed to exactly what the design supports.",
  assum:["Transparent about selection: exposure is not random and you say so.","Fixed effects absorb time-invariant confounders only.","Event studies need sharp, unanticipated shock dates."],
  robust:["District & year fixed effects; province-by-year trends.","Event studies around the largest discrete shocks.","Migration-sorting checks: composition vs. incidence.","Bounding exercises (Oster-style) for selection on unobservables."],
  pros:["Honest framing is publishable and respected","Often the truthful ceiling for observational conflict data"],
  cons:["No causal headline \u2014 and you must resist writing one","Referees may push for identification you cannot deliver"],
  refs:["Oster (2019), JBES","Abadie & Gardeazabal (2003), AER \u2014 for the synthetic-control alternative"]}
};

/* Secretary follow-up banks: one 'best' answer per method */
var ROBQ={
 did:{q:"\u201CFine \u2014 but how will you convince me the comparison districts were on the same path?\u201D",
  o:[{t:"An event-study plot: if pre-period leads are flat, the parallel-trends story has visible teeth.",best:true},
     {t:"I'll add more control variables until the coefficient stabilizes.",best:false,note:"Controls can't fix diverging trends \u2014 and coefficient stability is weak evidence."},
     {t:"A placebo outcome the program shouldn't touch, plus an alternative comparison group.",best:true},
     {t:"I'll just cluster the standard errors.",best:false,note:"Clustering fixes inference, not identification."}]},
 esdid:{q:"\u201CDistricts got the program at different times. How do I know timing wasn't chasing trends?\u201D",
  o:[{t:"Cohort-by-cohort event studies with Callaway\u2013Sant'Anna, plus a regression predicting rollout timing from observables.",best:true},
     {t:"Two-way fixed effects handles it automatically.",best:false,note:"Naive TWFE with staggered timing can even flip signs \u2014 that's the whole point of the new estimators."},
     {t:"Compare not-yet-treated as controls and show robustness to never-treated only.",best:true},
     {t:"Drop the early adopters.",best:false,note:"Ad hoc sample surgery invites suspicion."}]},
 rdd:{q:"\u201CClever. But what if families learned to game their scorecard number?\u201D",
  o:[{t:"A McCrary density test at the cutoff, covariate-smoothness plots, and a donut specification excluding the closest scores.",best:true},
     {t:"Manipulation is illegal, so it doesn't happen.",best:false,note:"Assume enumerators and households respond to incentives \u2014 then test."},
     {t:"Bandwidth and polynomial sensitivity with rdrobust.",best:true},
     {t:"I'll compare everyone above vs. below, full sample.",best:false,note:"That's just comparing poor and less-poor households \u2014 the discontinuity is local."}]},
 iv:{q:"\u201CRainfall, you say. Doesn't rain move health, migration, prices \u2014 everything?\u201D",
  o:[{t:"Exactly \u2014 so I'll defend exclusion explicitly, show placebo reduced forms where the channel is absent, and report weak-IV robust inference.",best:true},
     {t:"The first-stage F is above 10, so we're fine.",best:false,note:"Relevance \u2260 exclusion. The Secretary just named the real problem."},
     {t:"I'll interpret it honestly as a complier effect and probe each competing channel.",best:true},
     {t:"Everyone uses rainfall instruments.",best:false,note:"Tradition is not identification."}]},
 rct:{q:"\u201CAn experiment, in the field, on a student budget? Convince me it won't collapse.\u201D",
  o:[{t:"A signed partner MoU, a pre-analysis plan, a power calculation with an honest MDE, and an attrition-tracking protocol from day one.",best:true},
     {t:"We'll figure out sample size once we see the budget.",best:false,note:"Underpowered experiments waste everyone's consent."},
     {t:"Randomize at the cluster level to contain spillovers, and measure them where we can't.",best:true},
     {t:"IRB is a formality; we'll file it after baseline.",best:false,note:"Never after. Ethics clearance comes before any human contact."}]},
 panel:{q:"\u201CSo you admit you can't prove causation. Why should I fund description?\u201D",
  o:[{t:"Because honest, well-measured patterns \u2014 with event studies around sharp shocks and explicit bounds \u2014 beat a fake experiment every time.",best:true},
     {t:"I'll add district fixed effects; that makes it causal.",best:false,note:"Fixed effects absorb levels, not time-varying selection."},
     {t:"I'll separate composition from incidence \u2014 e.g., test whether migration sorting drives the pattern.",best:true},
     {t:"You're right; I'll claim causality anyway but hedge in a footnote.",best:false,note:"The footnote hedge fools no one and burns your credibility."}]}
};

/* ================= ACT 0 CONTENT ================= */
var CITIES=[
 {t:"Islamabad \u2014 desk at a Blue Area think tank, mountain view if you lean",geo:{federal:2},sub:"Policy briefs, donor meetings, and the PIDE seminar circuit."},
 {t:"Lahore \u2014 a university office off Ferozepur Road, permanent chai supply",geo:{punjab:2},sub:"Punjab's big administrative datasets are a rickshaw ride away."},
 {t:"Karachi \u2014 shared workspace near Shahrah-e-Faisal, sea breeze optional",geo:{sindh:2},sub:"The economy's engine room; informality everywhere you look."},
 {t:"Quetta \u2014 a small research cell that punches above its weight",geo:{balochistan:2},sub:"The hardest data environment \u2014 and the most under-studied questions."},
 {t:"Peshawar \u2014 office near University Road, kahwa instead of chai",geo:{kp:2},sub:"Merged districts, big reforms, live policy questions."}];
var ROLES=[
 {t:"Ministry research analyst",sub:"You draft summaries a Secretary might actually read.",tags:{horizon:{policy:2},data:{admin:1}}},
 {t:"Think-tank research associate",sub:"You live in Stata and seminar Q&As.",tags:{horizon:{paper:2},causal:{quasi:1}}},
 {t:"NGO monitoring & evaluation officer",sub:"You've seen programs from the inside \u2014 warts and all.",tags:{data:{primary:2},causal:{experimental:1}}},
 {t:"University research assistant",sub:"Thesis deadline on the horizon, curiosity intact.",tags:{horizon:{thesis:2}}}];

var OBQ=[
 {q:"Sunday morning, dhaba table, three newspapers. Which story do you read first?",
  o:[{t:"\u201CGirls' school enrollment stalls in south Punjab despite stipends\u201D",tags:{theme:{education:2,gender:1}}},
     {t:"\u201CSehat Card claims triple \u2014 but is anyone actually healthier?\u201D",tags:{theme:{health:2}}},
     {t:"\u201CTwo years after the floods, Dadu's farmers still can't plant\u201D",tags:{theme:{climate:2,poverty:1}}},
     {t:"\u201CPatwari culture survives computerization, land buyers complain\u201D",tags:{theme:{governance:2}}},
     {t:"\u201CMinimum wage notified again \u2014 and again ignored in workshops\u201D",tags:{theme:{labor:2}}}]},
 {q:"Last Eid, back in your family's home district, what quietly bothered you most?",
  o:[{t:"Your cousin \u2014 sharpest kid in the family \u2014 left school after Matric; nobody blinked.",tags:{theme:{education:2},geo:{}}},
     {t:"Your phupho traveled 40 km for a delivery because the local BHU had no lady doctor.",tags:{theme:{health:2,gender:1}}},
     {t:"An uncle's land transfer took eleven months and three \u201Cfees\u201D nobody names aloud.",tags:{theme:{governance:2}}},
     {t:"Half the young men were gone \u2014 Karachi, Dubai, anywhere \u2014 and the fields showed it.",tags:{theme:{labor:2,climate:1}}},
     {t:"Your cousin's wedding was moved up a year \u2014 she was seventeen.",tags:{theme:{gender:2,education:1}}}]},
 {q:"At a family dinner, an uncle declares a government program \u201Ctotal failure.\u201D Which one would you actually defend with evidence?",
  o:[{t:"BISP / Ehsaas Kafaalat \u2014 cash straight to women's accounts",tags:{theme:{poverty:2,gender:1}}},
     {t:"Sehat Sahulat \u2014 the health insurance card",tags:{theme:{health:2}}},
     {t:"Punjab's girls' stipend and school programs",tags:{theme:{education:2,gender:1}}},
     {t:"Land record computerization (LRMIS)",tags:{theme:{governance:2}}},
     {t:"Honestly? None yet \u2014 I'd want to see the evaluations first.",tags:{causal:{quasi:1}},sub:"A respectable answer."}]},
 {q:"That same uncle: \u201CObviously the stipend worked \u2014 enrollment went UP after it started!\u201D You reply\u2026",
  o:[{t:"\u201CEnrollment was rising everywhere, chacha. Show me districts WITHOUT the stipend first.\u201D",tags:{causal:{quasi:2}},sub:"Comparison-group instinct."},
     {t:"\u201CIf I ran things, I'd pilot it randomly in some union councils and compare.\u201D",tags:{causal:{experimental:2}},sub:"Experimentalist instinct."},
     {t:"\u201CLet me pull the district data tonight and see the pattern properly.\u201D",tags:{causal:{quasi:1},data:{survey:1}},sub:"Data-first instinct."},
     {t:"\u201CYou're probably right, chacha.\u201D (You are not proud of this.)",tags:{causal:{descriptive:1}},sub:"Peace at dinner has a price."}]},
 {q:"A friendly official says: \u201CI can get you ONE of these.\u201D You grab\u2026",
  o:[{t:"A hard drive of administrative records \u2014 school census, hospital claims, land mutations",tags:{data:{admin:2}}},
     {t:"Clean access to the big national surveys \u2014 PSLM, LFS, PDHS",tags:{data:{survey:2}}},
     {t:"A small budget and permission to run my own survey or field experiment",tags:{data:{primary:2},causal:{experimental:1}}},
     {t:"Satellite & geocoded layers \u2014 rainfall, floods, nightlights, incidents",tags:{data:{geo:2}}}]},
 {q:"Your supervisor offers three desks. Which do you take?",
  o:[{t:"The sprint desk: a sharp 6-month policy analysis a department will actually use",tags:{horizon:{policy:2}}},
     {t:"The thesis desk: 12\u201318 months, one question done properly, defense-ready",tags:{horizon:{thesis:2}}},
     {t:"The long-game desk: aim at a journal, take the extra year if needed",tags:{horizon:{paper:2}}}]}
];

var WISHMAP=[[/school|teacher|taleem|parh|education|enroll|exam|literacy/i,{education:2}],
 [/girl|women|aurat|larki|khawateen|gender|marriage|jahez|harass/i,{gender:2}],
 [/hospital|doctor|sehat|health|dawai|clinic|stunt|nutrition|polio|vaccin/i,{health:2}],
 [/flood|selab|smog|pollution|climate|barish|drought|garmi|heat|water/i,{climate:2}],
 [/poverty|ghurbat|bisp|ehsaas|rashan|cash|inflation|mehngai/i,{poverty:2}],
 [/job|naukri|rozgar|wage|tankhwah|labor|labour|mazdoor|unemploy|migra/i,{labor:2}],
 [/police|thana|court|kachehri|patwari|corruption|rishwat|governance|tax|land/i,{governance:2}],
 [/terror|dehshat|attack|conflict|security|aman|blast|militan/i,{conflict:2}]];

/* ================= ACT 1: FIELD DIARY SCENES ================= */
var SCENES=[
 {id:"muzaffargarh",kick:"Rural South Punjab \u00B7 October",title:"Cotton Season in Muzaffargarh",primary:"education",geo:{punjab:1},
  text:"Picking season. The government girls' school you're visiting is half empty; the headmistress shrugs \u2014 \u201Ckapaas ke din hain.\u201D Outside, children move down cotton rows beside their mothers. A landlord's munshi logs sacks in a register. Someone mentions the stipend money came late again this quarter.",
  q:"You have one hour and one notebook. What do you chase?",
  o:[{t:"The attendance registers: how many girls vanish every October, and do they come back?",tags:{theme:{education:2,gender:1}},note:"Seasonal absence might be the real dropout story."},
     {t:"The household math: what does a child-day of picking pay versus the stipend?",tags:{theme:{labor:2,poverty:1}},note:"Opportunity cost, made flesh."},
     {t:"The late stipend: who decides payment timing, and does delay change behavior?",tags:{theme:{education:1,governance:1},data:{admin:1}},note:"Implementation as a research question."},
     {t:"The pesticide drums by the field: what's picking season doing to health?",tags:{theme:{health:2}},note:"An environmental-health angle few study."}],
  follow:{q:"The headmistress offers you her old registers \u2014 ten years, handwritten. You\u2026",
  o:[{t:"Photograph every page. A decade of daily attendance is identification gold.",tags:{data:{admin:2},causal:{quasi:1}}},
     {t:"Ask instead which YEARS felt different \u2014 stipend changes, floods, road paving \u2014 hunting for natural experiments.",tags:{causal:{quasi:2}}},
     {t:"Politely note them, but plan a proper household survey \u2014 registers miss the never-enrolled.",tags:{data:{primary:2}}}]}},
 {id:"orangi",kick:"Urban Sindh \u00B7 Karachi",title:"A Lane in Orangi Town",primary:"labor",geo:{sindh:1},
  text:"Inside a two-room house, three women stitch football-club shirts for a contractor who pays by the dozen. Next door, a private school charges Rs. 900 a month and is full. The water tanker arrives \u2014 everyone pays cash; the government line has been dry for years.",
  q:"What's your first question, and to whom?",
  o:[{t:"To the women: what would it take \u2014 wage, safety, childcare \u2014 to work outside the home?",tags:{theme:{gender:2,labor:1}},note:"The FLFP puzzle, asked at its source."},
     {t:"To the contractor: how does piece-rate pay move when export orders shift?",tags:{theme:{labor:2}},note:"Global demand meets a Karachi lane."},
     {t:"To the school owner: who chooses private over government here, and why?",tags:{theme:{education:2}},note:"The low-cost private school revolution."},
     {t:"To the tanker driver: who profits when public water fails?",tags:{theme:{governance:2}},note:"Service failure as an equilibrium."}],
  follow:{q:"One of the women says, half-joking: \u201CWrite that my daughters will do better than this.\u201D What would count as evidence, for her?",
  o:[{t:"Track daughters vs. mothers: schooling, age at marriage, first job \u2014 intergenerational mobility, measured.",tags:{theme:{gender:1,education:1},horizon:{paper:1}}},
     {t:"Evaluate one concrete lever \u2014 a training program, a transport service \u2014 against a real comparison group.",tags:{causal:{experimental:1,quasi:1}}},
     {t:"Document the piece-rate economy honestly first; you can't fix what's uncounted.",tags:{causal:{descriptive:1},data:{primary:1}}}]}},
 {id:"dadu",kick:"Flood-affected Sindh \u00B7 Dadu",title:"Two Winters After the Water",primary:"climate",geo:{sindh:1},
  text:"The 2022 flood line is still visible on the walls \u2014 chest height. Half the village took the Rs. 25,000 emergency cash; the other half swears the survey teams never came. The school reopened in a tent. Several families simply never returned from the Hyderabad bypass camps.",
  q:"The visit is short. What do you document?",
  o:[{t:"Who got the flood cash and who didn't \u2014 and whether that line was drawn fairly.",tags:{theme:{poverty:2,governance:1}},note:"Targeting under emergency conditions."},
     {t:"Which families left for good \u2014 and what marks the leavers from the stayers.",tags:{theme:{climate:1,labor:2}},note:"Climate migration, at the household level."},
     {t:"The children's learning: two school years disrupted \u2014 what's the damage and can it be measured?",tags:{theme:{education:2,climate:1}},note:"Human capital under water."},
     {t:"Water sources now vs. before: what are people drinking, and who is sick?",tags:{theme:{health:2,climate:1}},note:"The slow disaster after the fast one."}],
  follow:{q:"A satellite map on your phone shows exactly which fields flooded, meter by meter. That precision is exciting because\u2026",
  o:[{t:"Flood extent is plausibly as-good-as-random within small areas \u2014 comparison groups drawn by water, not by choice.",tags:{causal:{quasi:2},data:{geo:2}}},
     {t:"I can merge it with household surveys and build a before/after panel of villages.",tags:{data:{geo:1,survey:1}}},
     {t:"It's a map the Deputy Commissioner can act on next monsoon \u2014 policy first.",tags:{horizon:{policy:1}}}]}},
 {id:"pishin",kick:"Balochistan \u00B7 Pishin",title:"The Girls' School at the Edge of Town",primary:"education",geo:{balochistan:1},
  text:"Sixty girls, two teachers \u2014 one on long leave, unfilled for a year. The van that brought girls from three villages stopped when the fuel stipend lapsed. The headmistress keeps a list of former students: married, working at home, one \u2014 she says with fierce pride \u2014 at Sardar Bahadur Khan University.",
  q:"What thread do you pull?",
  o:[{t:"The teacher post: how long do vacancies sit unfilled here versus in Quetta, and why?",tags:{theme:{education:1,governance:2}},note:"The state's presence, measured in vacancies."},
     {t:"The van: does transport, not tuition, decide whether Baloch girls stay in school?",tags:{theme:{education:2,gender:1}},note:"Distance as the binding constraint."},
     {t:"The list: what separates the girl who reached university from her classmates?",tags:{theme:{gender:2,education:1}},note:"Outliers teach."},
     {t:"The lapsed stipend: trace the money \u2014 where exactly did it stall?",tags:{theme:{governance:2},data:{admin:1}},note:"Follow the file."}],
  follow:{q:"The headmistress asks, not unkindly: \u201CResearchers came in 2019 too. What will YOU leave behind?\u201D",
  o:[{t:"A number the department can't ignore \u2014 the enrollment cost of one unfilled post or one stopped van.",tags:{horizon:{policy:2}}},
     {t:"A study designed so the comparison is airtight \u2014 evidence that survives a hostile committee.",tags:{causal:{quasi:2}}},
     {t:"Her school in the sample \u2014 and the report back in her hands, in Urdu, before anyone publishes.",tags:{data:{primary:1}},note:"Research ethics, the practical kind."}]}},
 {id:"merged",kick:"Khyber Pakhtunkhwa \u00B7 Merged District",title:"After the Merger",primary:"conflict",geo:{kp:1},
  text:"Since 2018 this former FATA agency has been a settled district on paper. A new judicial complex stands half-finished. An elder explains land ownership here was never written down \u2014 \u201Chum jaante the kiska kya hai.\u201D A young returnee runs a mobile-repair shop and says, carefully, that things are calmer than the news suggests.",
  q:"The merger is a once-in-a-generation policy shock. What's the sharpest question in it?",
  o:[{t:"Did the extension of courts and settled law change how disputes get resolved \u2014 and who wins them?",tags:{theme:{governance:2,conflict:1}},note:"State-building, observed in real time."},
     {t:"Public services after merger: are schools, BHUs, NADRA vans actually arriving faster than before?",tags:{theme:{education:1,health:1,conflict:1}},note:"The service-delivery dividend, if any."},
     {t:"Security and the local economy: as incidents fell, did shops, prices, and jobs respond?",tags:{theme:{conflict:2,labor:1}},note:"The peace dividend, priced."},
     {t:"Returnee families: who came back after displacement, and how are their children doing?",tags:{theme:{conflict:2,education:1}},note:"Displacement's long shadow."}],
  follow:{q:"You realize old household surveys mostly EXCLUDED these areas. That gap is\u2026",
  o:[{t:"A problem to solve with creativity \u2014 satellite proxies, new admin data, the 2019-20 PSLM's first merged-district coverage.",tags:{data:{geo:1,admin:1}},note:"Constraints breed designs."},
     {t:"A reason to collect primary data here \u2014 carefully, with local partners and real ethics review.",tags:{data:{primary:2}}},
     {t:"Itself a finding: who gets counted is a political outcome worth writing about.",tags:{theme:{governance:1},causal:{descriptive:1}}}]}},
 {id:"kachehri",kick:"Punjab \u00B7 District Courts",title:"Morning at the Kachehri",primary:"governance",geo:{punjab:1},
  text:"Under the banyan trees, stamp-paper vendors and arz-navees do brisk business. A retired schoolteacher shows you his file: a land case, eleven years old, forty-one hearings, still \u201Cfixed for evidence.\u201D Inside, a young judge's new cause-list system prints neat schedules nobody quite follows yet.",
  q:"What do you count?",
  o:[{t:"Case lifecycles: filing to disposal, hearing by hearing \u2014 where exactly does time die?",tags:{theme:{governance:2},data:{admin:2}},note:"The delay, decomposed."},
     {t:"The land cases specifically: does the computerized record (LRMIS) change what gets disputed?",tags:{theme:{governance:2}},note:"Property rights meet the server."},
     {t:"Who gives up: which litigants abandon claims, and what does that cost the poor?",tags:{theme:{poverty:1,governance:1}},note:"Justice rationed by stamina."},
     {t:"The new cause-list system itself \u2014 a reform rolling out court by court. A natural experiment?",tags:{causal:{quasi:2},data:{admin:1}},note:"Rollouts are your friend."}],
  follow:{q:"A court clerk, amused: \u201CYou want our registers? Which YEARS?\u201D The sharp answer is\u2026",
  o:[{t:"\u201CThe years around each reform \u2014 before and after, for courts that got it early AND late.\u201D",tags:{causal:{quasi:2}},note:"You just described a staggered rollout design."},
     {t:"\u201CAll of them \u2014 the full panel. Let the data reveal the breaks.\u201D",tags:{data:{admin:2}}},
     {t:"\u201CHonestly, this year's \u2014 I need something a policy note can use by June.\u201D",tags:{horizon:{policy:1}}}]}},
 {id:"bhu",kick:"Rural Sindh \u00B7 Basic Health Unit",title:"The BHU at Eleven A.M.",primary:"health",geo:{sindh:1},
  text:"The Lady Health Worker's register is meticulous \u2014 every pregnancy in her cluster, every missed vaccination underlined twice. The doctor's chair is empty (\u201Cwoh Karachi mein hain\u201D). A grandmother argues about her Sehat Card: the private hospital in town took it, the closer one refused.",
  q:"Where's the research question hiding?",
  o:[{t:"In the empty chair: absenteeism \u2014 who monitors it, and does monitoring work?",tags:{theme:{health:1,governance:2}},note:"A classic, still unsolved."},
     {t:"In the Sehat Card: is insurance moving people from BHUs to private hospitals \u2014 and does that help or hurt?",tags:{theme:{health:2}},note:"Insurance changes WHERE care happens."},
     {t:"In the LHW's register: a woman-run data system that actually works \u2014 what does it enable?",tags:{theme:{gender:1,health:1},data:{admin:1}},note:"Frontline female state capacity."},
     {t:"In the underlined names: which children miss vaccinations, and what would move them?",tags:{theme:{health:2}},note:"The last-mile immunization gap."}],
  follow:{q:"The LHW says her register goes back nine years and she'll explain every column. You think\u2026",
  o:[{t:"Pair her micro-records with district claims data \u2014 admin depth plus survey breadth.",tags:{data:{admin:2}}},
     {t:"Her cluster boundaries could anchor a small experiment \u2014 reminders, incentives, transport vouchers.",tags:{causal:{experimental:2},data:{primary:1}}},
     {t:"Nine years spans the Sehat Card rollout \u2014 before/after, in one register.",tags:{causal:{quasi:2}}}]}},
 {id:"smog",kick:"Punjab \u00B7 Lahore, November",title:"Smog Season",primary:"climate",geo:{punjab:1},
  text:"The AQI app reads 412. Schools are closed by notification \u2014 again \u2014 though the tuition academies quietly run. A brick-kiln owner on the city's edge insists his new zigzag kiln is clean. Your rickshaw driver coughs the whole way and calls it \u201Cbas mausam hai.\u201D",
  q:"Everyone argues about smog; almost nobody measures its costs. Which cost would you pin down?",
  o:[{t:"School closures: lost days versus the tuition-academy workaround \u2014 who actually loses learning?",tags:{theme:{education:1,climate:1}},note:"The policy response has its own costs."},
     {t:"Health at the ER: do respiratory admissions track the AQI, day by day, district by district?",tags:{theme:{health:1,climate:1},data:{admin:1}},note:"High-frequency environmental health."},
     {t:"Outdoor labor: what happens to daily-wage earnings when the air turns grey?",tags:{theme:{labor:1,climate:1}},note:"The regressive tax nobody legislated."},
     {t:"The kilns: did the zigzag retrofit drive \u2014 kiln by kiln \u2014 actually cut emissions?",tags:{theme:{climate:2},causal:{quasi:1}},note:"A rollout with GPS coordinates."}],
  follow:{q:"You find hourly PM2.5 archives from monitors around the city. The honest limitation to write down first is\u2026",
  o:[{t:"Exposure isn't random \u2014 the poor live and work closer to the sources \u2014 so I need a design, not a correlation.",tags:{causal:{quasi:2}},note:"Selection named before it names you."},
     {t:"Monitor coverage is thin outside big cities; I'll say clearly where my data can and cannot speak.",tags:{causal:{descriptive:1}}},
     {t:"Behavior responds \u2014 masks, closures, staying in \u2014 so I'm estimating effects net of avoidance.",tags:{causal:{quasi:1}}}]}}
];

/* ================= THEME & DESIGN LIBRARY ================= */
var PROV={punjab:"Punjab",sindh:"Sindh",kp:"Khyber Pakhtunkhwa",balochistan:"Balochistan",federal:"Islamabad / federal"};
var THEMES={
education:{label:"Education & Learning",sdg:"SDG 4.1 (completion), 4.5 & 5.1 (gender parity)",
 uraan:"Equity & Empowerment pillar, URAAN Pakistan (5Es)",
 prov:"Provincial hooks: Punjab school-reform roadmap & PMIU monitoring; Sindh SESP; KP Education Sector Plan; the national out-of-school-children emergency (~26 million).",
 designs:[
 {id:"e1",m:"did",feas:"High",feasNote:"All data free and public; identification well-trodden but extendable.",
  title:"Cash for Class: The Punjab Female School Stipend and Girls' Schooling",
  rq:"Did Punjab's Female School Stipend Programme (from 2004, paid in low-literacy districts for girls in grades 6\u20138) raise girls' middle-school enrollment and completion \u2014 and did it shift the timing of marriage?",
  sub:["Do effects differ by distance to the nearest girls' middle school?","Any spillovers to boys or to private-school enrollment?","Long-run: completion, marriage age and fertility for exposed cohorts (via later PSLM/PDHS waves)."],
  hook:"Stipend programs are Pakistan's flagship girls'-education lever, now echoed in Waseela-e-Taleem and provincial schemes. Two decades on, the long-run and margin-specific evidence is thinner than the policy's popularity \u2014 exactly the gap a careful thesis can fill.",
  data:["pslm_d","aser","admin","census"],
  ident:"Difference-in-differences comparing the 15 stipend districts to non-stipend Punjab districts before vs. after 2004, estimated on pooled PSLM district rounds. Strengthen with (i) an event-study specification, (ii) a difference-in-discontinuity design around the female-literacy eligibility threshold used to select districts, and (iii) a cohort-exposure design (age at program start) for long-run outcomes.",
  eq:"Enroll_gdt = \u03B1_d + \u03BB_t + \u03B2\u00B7(Stipend_d \u00D7 Post_t) + X\u2032_gdt\u03B8 + \u03B5_gdt   (girl g, district d, wave t; cluster by district)",
  threats:[{t:"Districts were chosen for low literacy \u2014 mean reversion could mimic effects.",m:"Event-study pre-trends; difference-in-discontinuity at the selection threshold; permutation inference."},
   {t:"Contemporaneous programs (school construction, free textbooks).",m:"Control for school-supply measures from EMIS; test timing against program calendars."},
   {t:"Selective migration into stipend districts.",m:"Check district population composition (census, PSLM migration module)."},
   {t:"Enrollment \u2260 attendance or learning.",m:"Bring in ASER attendance and learning outcomes as complementary endpoints."}],
  anchors:["Alam, Baez & Del Carpio (2011), World Bank Policy Research WP \u2014 the original FSSP evaluation","Chaudhury & Parajuli (2010), Applied Economics","Andrabi, Das & Khwaja (2017), AER \u2014 report cards & Punjab school markets","Callaway & Sant'Anna (2021), Journal of Econometrics"],
  ext:["Compare cost-effectiveness against Waseela-e-Taleem's demand-side transfer.","Marriage-market outcomes for exposed cohorts in PDHS.","KP and Sindh stipend variants as replication sites."],flags:{}},
 {id:"e2",m:"rdd",feas:"Medium",feasNote:"Needs a BISP/NSER data agreement (start early); OPM evaluation waves are a fallback.",
  title:"The Price of Attendance: Waseela-e-Taleem at the Scorecard Cutoff",
  rq:"What is the causal effect of BISP's conditional education stipend (Waseela-e-Taleem) on enrollment and attendance for children of households just below the NSER eligibility cutoff?",
  sub:["Are effects larger for girls (whose stipend is higher)?","Does the attendance condition (70%) bind \u2014 bunching in attendance records?","Do effects persist after children age out of the transfer?"],
  hook:"Waseela-e-Taleem is among the largest conditional cash transfers in South Asia, and its eligibility rule \u2014 a hard proxy-means-test cutoff \u2014 is a nationally important, ready-made regression discontinuity that Master's research can credibly exploit.",
  data:["nser","admin","aser","pslm_d"],
  ident:"Sharp (or fuzzy, using actual take-up) RDD at the PMT eligibility threshold, local-linear estimation with rdrobust bandwidths; RD-DiD variant using the program's district phase-in to separate the education stipend from the bundled Kafaalat cash.",
  eq:"Y_i = \u03C4\u00B71[PMT_i \u2264 c] + f(PMT_i \u2212 c) + \u03B5_i ,  |PMT_i \u2212 c| \u2264 h   (rdrobust; McCrary density test first)",
  threats:[{t:"Manipulation of PMT scores near the cutoff.",m:"McCrary/Cattaneo density test; donut RDD; covariate smoothness plots."},
   {t:"Compound treatment: the same cutoff triggers Kafaalat cash.",m:"Interpret as the bundled effect, or use Waseela's staggered district phase-in for separation."},
   {t:"Data access delays.",m:"Request early with institutional backing; fallback to published OPM evaluation microdata."},
   {t:"Local estimate only.",m:"Be explicit: effects at the cutoff population; compare covariates of compliers to the national poor."}],
  anchors:["Cheema et al. / Oxford Policy Management \u2014 BISP impact evaluation reports","Ambler & de Brauw (World Bank) \u2014 BISP and women's empowerment","Cattaneo, Idrobo & Titiunik (2020) \u2014 RDD foundations","Lee & Lemieux (2010), Journal of Economic Literature"],
  ext:["Nutrition top-up (Nashonuma) at the same cutoff.","Sibling spillovers within households.","Attendance-condition enforcement as its own experiment."],flags:{admin:true}},
 {id:"e3",m:"esdid",feas:"High",feasNote:"All layers open-access; the merge (flood polygons \u2192 villages) is the main skill investment.",
  title:"After the Water: The 2022 Floods and Foundational Learning",
  rq:"How much foundational learning (reading, arithmetic) did children in flood-inundated communities lose relative to observably similar dry communities \u2014 and is the gap closing?",
  sub:["Are losses larger for girls or for children who changed schools?","Did tent schools / catch-up programs buffer losses anywhere?","Enrollment vs. learning: which margin took the bigger hit?"],
  hook:"A third of the country was under water in 2022 and over 26,000 schools were damaged, yet credible causal estimates of the learning cost remain scarce. Satellite flood extents give researchers something rare: treatment drawn by water, not by choice.",
  data:["geo","aser","pslm_d","mics"],
  ident:"Event-study / difference-in-differences comparing ASER learning outcomes in villages inside vs. outside satellite-mapped inundation polygons, before and after 2022, with district fixed effects; dose-response using share of village area flooded.",
  eq:"Learn_ivt = \u03B1_v + \u03BB_t + \u03A3_k \u03B2_k\u00B7(Flooded_v \u00D7 1[t = 2022+k]) + \u03B5_ivt   (child i, village v, year t)",
  threats:[{t:"Flooded areas were poorer to begin with.",m:"Village fixed effects + pre-2022 trend checks; match on pre-flood ASER levels."},
   {t:"Out-migration changes who is tested.",m:"Track village composition; bound results for movers (composition vs. incidence)."},
   {t:"ASER coverage gaps in worst-hit areas.",m:"Report coverage explicitly; complement with PSLM/MICS enrollment."},
   {t:"Relief targeting correlated with flooding.",m:"Control for cash-relief district notifications; test sensitivity."}],
  anchors:["Andrabi, Daniels & Das (2023), Journal of Human Resources \u2014 the 2005 earthquake and human capital","ASER Pakistan annual reports","Dell, Jones & Olken (2014), JEL \u2014 climate\u2013economy toolkit"],
  ext:["Long-run tracking as post-2022 ASER rounds accumulate.","Heat and smog as slower-moving analogues.","School-reconstruction speed as a mediator (admin data)."],flags:{}}]},
gender:{label:"Gender & Empowerment",sdg:"SDG 5.1, 5.2, 5.a & 8.5",
 uraan:"Equity & Empowerment pillar, URAAN Pakistan (5Es)",
 prov:"Provincial hooks: women-payee design of BISP; provincial Commissions on the Status of Women; Punjab & Sindh women's economic empowerment policies; ~22-point gender gap in labor force participation.",
 designs:[
 {id:"g1",m:"rdd",feas:"Medium",feasNote:"Empowerment outcomes need OPM evaluation data or a small survey top-up within the RD bandwidth.",
  title:"Cash in Her Name: Kafaalat's Woman-Payee Rule and Intra-Household Power",
  rq:"Does receiving BISP Kafaalat \u2014 paid, by design, to the woman of the household \u2014 shift women's mobility, say in decisions, and financial access at the eligibility cutoff?",
  sub:["Do effects run through bank/BVS account ownership and CNIC acquisition?","Any change in attitudes toward, or reported incidence of, domestic violence?","Are effects stronger where baseline norms were most restrictive?"],
  hook:"Kafaalat is one of the world's largest woman-directed cash programs. Whether directing cash to women shifts power inside households \u2014 or just relabels the envelope \u2014 is a first-order question for every social-protection design in South Asia.",
  data:["nser","pdhs","admin"],
  ident:"Regression discontinuity at the NSER PMT cutoff on women's-empowerment outcomes, using OPM evaluation waves or a compact primary survey of households within the bandwidth; PDHS modules supply validated instruments for the empowerment indices.",
  eq:"Empower_w = \u03C4\u00B71[PMT_w \u2264 c] + f(PMT_w \u2212 c) + \u03B5_w   (woman w; index = decision-making, mobility, finance)",
  threats:[{t:"Empowerment indices are survey-fragile.",m:"Use PDHS-validated modules; pre-specify index construction; anchoring vignettes if collecting primary data."},
   {t:"Reporting effects on sensitive items (DV).",m:"Follow DHS ethical protocols; interpret attitude vs. incidence separately; list experiments if primary."},
   {t:"Score manipulation at cutoff.",m:"Density and covariate-smoothness tests."},
   {t:"Cash vs. woman-payee bundling.",m:"Frame estimand honestly: effect of woman-directed cash, not payee identity alone."}],
  anchors:["Ambler & de Brauw (World Bank) \u2014 BISP and women's empowerment","Gin\u00E9 & Mansuri (2018), AEJ: Applied \u2014 women's voting in Pakistan","Bursztyn, Gonz\u00E1lez & Yanagizawa-Drott (2020), AER \u2014 misperceived norms","Jayachandran (2021), IMF Economic Review \u2014 norms and women's work"],
  ext:["Mobile-wallet payment rollout as a second experiment.","Daughters' schooling and marriage timing as downstream outcomes.","Norm spillovers to neighboring ineligible households."],flags:{admin:true}},
 {id:"g2",m:"did",feas:"Medium",feasNote:"ECP gender-disaggregated turnout is public; CNIC-drive timing needs NADRA/press reconstruction.",
  title:"The Card and the Vote: Women's CNIC Drives and the Gender Turnout Gap",
  rq:"Did district-level campaigns to register women for national identity cards (CNICs) narrow the female\u2013male turnout gap in subsequent general elections?",
  sub:["Effects on women's registration first (first stage), then turnout.","Do effects persist across election cycles?","Heterogeneity by baseline gender gap and rurality."],
  hook:"Millions of Pakistani women historically lacked the CNIC required to vote, open accounts, or receive BISP. Since 2018, gender-disaggregated turnout is published per polling station \u2014 a rare measurement window on women's political inclusion.",
  data:["admin","census","lfs"],
  ident:"Difference-in-differences / event study across districts by timing and intensity of women's CNIC registration drives (NADRA mobile-van deployments), with electoral-cycle fixed effects; polling-station panels sharpen power.",
  eq:"Gap_dt = \u03B1_d + \u03BB_t + \u03B2\u00B7Drive_d,t\u2212 + \u03B5_dt   (female\u2212male turnout gap, district d, election t)",
  threats:[{t:"Drives targeted where gaps were worst \u2014 selection.",m:"Event-study leads; control for lagged gap; use van-capacity constraints as quasi-random intensity."},
   {t:"Concurrent mobilization (parties, BISP enrollment).",m:"Timeline controls; placebo on male turnout."},
   {t:"Polling-station boundary changes.",m:"Aggregate to stable constituencies; boundary crosswalks."},
   {t:"Registration \u2260 autonomous voting.",m:"Discuss mechanisms; pair with survey evidence on mobility."}],
  anchors:["Gin\u00E9 & Mansuri (2018), AEJ: Applied","ECP gender-wise turnout publications","CERP/IDEAS field studies on women's electoral participation in Punjab"],
  ext:["Downstream effects: bank accounts, BISP receipt, property registration.","Local-election outcomes.","Candidate responses in high-drive districts."],flags:{admin:true}},
 {id:"g3",m:"rct",feas:"Ambitious",feasNote:"Needs a partner organization, IRB approval, and a semester of fieldwork \u2014 high risk, high learning.",
  title:"What Husbands Think Husbands Think: Misperceived Norms and Women's Work",
  rq:"Do men systematically overestimate other men's opposition to women working outside the home \u2014 and does correcting that misperception change real job-search behavior by their wives?",
  sub:["How large is the wedge between actual and perceived norms, by community?","Does information move stated support, costly sign-ups, or both?","Do effects decay or diffuse over three months?"],
  hook:"Pakistan's female labor force participation (~25%) sits far below regional peers. If part of the constraint is a misperceived norm \u2014 each man privately more permissive than he believes his neighbors are \u2014 then cheap information can move a margin that subsidies cannot.",
  data:["lfs","pdhs"],
  ident:"Individual-randomized information experiment (adapted from Bursztyn et al. 2020): elicit first- and second-order beliefs, randomize revelation of true community support rates, measure a costly outcome \u2014 sign-up of the wife for a verified job-matching or training service.",
  eq:"Y_i = \u03B1 + \u03B2\u00B7Info_i + X\u2032_i\u03B8 + \u03B5_i   (pre-registered; randomization inference; Lee bounds for attrition)",
  threats:[{t:"Experimenter demand.",m:"Costly/behavioral outcome (sign-up), not stated attitudes; neutral framing; list-method checks."},
   {t:"Attrition and spillovers within mohallas.",m:"Cluster-aware design; track attriters; measure second-hand exposure."},
   {t:"Ethics of household-level intervention.",m:"Full IRB review; women's consent independently obtained; safeguarding referral protocol."},
   {t:"Small-sample power.",m:"Honest MDE calculation before launch; single primary outcome."}],
  anchors:["Bursztyn, Gonz\u00E1lez & Yanagizawa-Drott (2020), AER","Jayachandran (2021), IMF Economic Review","Field & Vyborny \u2014 CERP work on women's mobility and transport in Lahore","Glennerster & Takavarasha \u2014 Running Randomized Evaluations"],
  ext:["Norm-correction via respected local messengers.","Transport bundling (subsidized pick-up) as a cross-cut arm.","Employer-side beliefs as a mirror experiment."],flags:{primary:true}}]},
health:{label:"Health & Nutrition",sdg:"SDG 3.1, 3.2 & 3.8 (UHC)",
 uraan:"Equity & Empowerment pillar, URAAN Pakistan (5Es)",
 prov:"Provincial hooks: KP's universal Sehat Card (from Nov 2020) and Punjab's expansion; ~40% child stunting; immunization last-mile gaps; catastrophic out-of-pocket health spending.",
 designs:[
 {id:"h1",m:"esdid",feas:"High",feasNote:"Rollout dates are public; HIES/PSLM are free \u2014 a genuinely feasible flagship thesis.",
  title:"The Card at the Ward: Sehat Sahulat and Household Health Spending",
  rq:"Did the staggered district rollout of Sehat Sahulat health insurance reduce out-of-pocket health spending and catastrophic expenditure \u2014 and did it shift where households seek care?",
  sub:["Effects on hospitalization rates and private vs. public utilization (PSLM).","Did protection reach the poorest quintiles?","Any crowd-out of preventive/outpatient care (which the card does not cover)?"],
  hook:"Sehat Sahulat is Pakistan's boldest step toward universal health coverage \u2014 KP went universal in November 2020, Punjab followed \u2014 yet its household-finance effects are mostly asserted, not estimated. The district-by-district rollout is a textbook staggered-adoption design.",
  data:["hies","pslm_d","admin","mics"],
  ident:"Staggered difference-in-differences across districts by insurance launch date, estimated with Callaway\u2013Sant'Anna group-time ATTs on HIES out-of-pocket spending (2015-16, 2018-19, 2024-25) and PSLM utilization; naive TWFE reported alongside for contrast.",
  eq:"ATT(g,t) per Callaway\u2013Sant'Anna;  headline: ln(OOP_hdt) on rollout exposure, district & wave FE",
  threats:[{t:"Rollout order was political, not random.",m:"Predict launch timing with observables; cohort event-studies; not-yet-treated controls."},
   {t:"Long HIES gap (2018-19 \u2192 2024-25) spans COVID and floods.",m:"Province-by-year controls; triangulate with annual claims admin data."},
   {t:"Supply response confounds demand protection.",m:"Track empanelled-hospital counts; separate price vs. utilization margins."},
   {t:"Reporting of health spending is noisy.",m:"Catastrophic-spending indicators (>10%/25% of consumption) as robust endpoints."}],
  anchors:["Callaway & Sant'Anna (2021); Sun & Abraham (2021)","King et al. (2009), The Lancet \u2014 Mexico's Seguro Popular evaluation","Goodman-Bacon (2021) \u2014 why naive TWFE misleads here"],
  ext:["Claims-data deep dive (procedures, moral hazard) under an MoU.","Health outcomes (PDHS/MICS) as slower-moving endpoints.","Distributional incidence: who gains most from the card?"],flags:{}},
 {id:"h2",m:"esdid",feas:"Medium",feasNote:"All data open; framing must stay careful and apolitical.",
  title:"Missed Jabs: Local Insecurity and Childhood Immunization",
  rq:"Do spikes in local violence \u2014 especially attacks touching health campaigns \u2014 reduce childhood immunization completion in affected districts, and for how long?",
  sub:["Routine EPI vs. campaign (polio) doses: which margin suffers?","Do effects persist after violence subsides?","Are girls' vaccinations differentially affected?"],
  hook:"Pakistan is one of the last polio-endemic countries, and attacks on vaccinators have repeatedly paused campaigns. Quantifying the immunization cost of insecurity gives health planners a concrete number for protection and catch-up budgeting.",
  data:["geo","pslm_d","pdhs","mics"],
  ident:"Event-study around large geocoded incidents (GTD/PIPS) affecting district campaign windows, on immunization outcomes from PSLM/MICS child rosters; district and cohort fixed effects; dose-response in incident intensity.",
  eq:"Immun_cdt = \u03B1_d + \u03BB_t + \u03A3_k \u03B2_k\u00B7Incident_d \u00D7 1[t = k] + \u03B5_cdt   (child c born into window t)",
  threats:[{t:"Violence correlates with poverty and remoteness.",m:"District FE absorb levels; leads test pre-trends; within-district cohort comparisons."},
   {t:"Under-reporting of incidents in remote areas.",m:"Cross-validate GTD against PIPS; robustness to incident-source choice."},
   {t:"Displacement changes who is surveyed.",m:"Composition checks via migration modules; bound estimates."},
   {t:"Campaign suspensions are administrative choices.",m:"Treat suspension as mechanism, not treatment; document both."}],
  anchors:["Public-health literature on insecurity and vaccination coverage in Pakistan","Abadie & Gardeazabal (2003), AER \u2014 conflict-cost framing","PIPS annual security reports"],
  ext:["Lady-Health-Worker coverage as a resilience factor.","Facility births and antenatal care as parallel outcomes.","Catch-up campaign effectiveness after pauses."],flags:{}},
 {id:"h3",m:"rdd",feas:"Ambitious",feasNote:"Anthropometrics require primary measurement or special-module access \u2014 pair with a supervisor's project.",
  title:"Feeding the Curve: Nashonuma's Nutrition Transfer and Child Growth",
  rq:"Does the Nashonuma conditional nutrition top-up (cash + specialized food, tied to clinic visits) improve child growth outcomes at the NSER eligibility cutoff?",
  sub:["Compliance first: do clinic visits and food collection actually rise?","Effects on height-for-age vs. weight-for-height (chronic vs. acute).","Does the mother's-visit condition change other care-seeking?"],
  hook:"With stunting near 40%, Pakistan's nutrition problem is a national-security-grade issue \u2014 URAAN says so explicitly. Nashonuma bolts a nutrition condition onto the Kafaalat cutoff, creating a rare RD design for biology, not just behavior.",
  data:["nser","pdhs","admin"],
  ident:"Fuzzy RDD at the PMT cutoff with program take-up as first stage; outcomes from facility growth-monitoring records or a measured-anthropometrics survey within the RD bandwidth.",
  eq:"HAZ_c = \u03C4\u00B7Take-up_c + f(PMT_c \u2212 cutoff) + \u03B5_c   (fuzzy RD; take-up instrumented by eligibility)",
  threats:[{t:"Anthropometric measurement error.",m:"Trained enumerators, standardized boards/scales, repeat measures on a subsample."},
   {t:"Facility records reflect selective attendance.",m:"Model attendance explicitly; survey non-attenders in bandwidth."},
   {t:"Slow biology vs. short thesis clock.",m:"Weight-for-height and MUAC as faster-moving endpoints; be honest on horizon."},
   {t:"Bundled with Kafaalat cash.",m:"Interpret as marginal effect of the nutrition layer where phase-in permits."}],
  anchors:["Cattaneo, Idrobo & Titiunik (2020)","OPM \u2014 BISP evaluation instruments for anthropometrics","PDHS 2017-18 nutrition module documentation"],
  ext:["Sibling spillovers on diet composition.","LHW counseling as a complementary arm.","Cost per case of stunting averted."],flags:{primary:true,admin:true}}]},
poverty:{label:"Poverty & Social Protection",sdg:"SDG 1.2, 1.3 & 10.1",
 uraan:"Equity & Empowerment pillar, URAAN Pakistan (5Es)",
 prov:"Provincial hooks: BISP/Ehsaas as the federal backbone; post-flood cash operations; inflation's bite on real consumption since 2022; the 2024-25 HIES as the first post-shock poverty read.",
 designs:[
 {id:"p1",m:"rdd",feas:"Medium",feasNote:"The famous 16.17 cutoff is the cleanest RD in Pakistani policy \u2014 access is the only real barrier.",
  title:"Sixteen Point One Seven: Household Life at the Scorecard Cutoff",
  rq:"What are the effects of sustained Kafaalat cash on consumption, child labor, and school enrollment for households just below the NSER eligibility cutoff?",
  sub:["Consumption smoothing vs. investment: where does the cash go?","Does child labor fall, and whose \u2014 boys' or girls'?","Debt and informal-credit reliance at the threshold."],
  hook:"BISP's proxy-means-test cutoff has decided, for over a decade, which of two nearly identical families gets a quarterly transfer. That administrative knife-edge is the country's most important natural experiment in social protection.",
  data:["nser","hies","pslm_d"],
  ident:"RDD at the PMT threshold; outcomes from OPM evaluation rounds, or from linking scorecard bands to a compact primary survey of bandwidth households; fuzzy variant using actual payment receipt.",
  eq:"Y_h = \u03C4\u00B71[PMT_h \u2264 16.17] + f(PMT_h \u2212 16.17) + \u03B5_h   (household h within bandwidth)",
  threats:[{t:"Cutoff manipulation and enumerator discretion.",m:"Density tests by survey vintage (2010-11 vs. dynamic registry); donut RD."},
   {t:"Multiple programs share the cutoff.",m:"Estimand = the bundled Ehsaas package; use program phase-ins for partial separation."},
   {t:"Old registry, changed households.",m:"Prefer dynamic-registry scores; document re-survey rules."},
   {t:"Access timeline risk.",m:"Parallel-track: OPM public data analysis while the MoU processes."}],
  anchors:["OPM \u2014 BISP impact evaluation series","Ambler & de Brauw (World Bank)","Cattaneo, Idrobo & Titiunik (2020)","Banerjee et al. \u2014 cash-transfer evidence reviews"],
  ext:["Graduation/asset-transfer pilots comparison.","Inflation pass-through: real transfer value over time.","Political economy: does receipt shift trust in the state?"],flags:{admin:true}},
 {id:"p2",m:"esdid",feas:"Medium",feasNote:"Notified-district lists and satellite layers are public; outcome data is the binding choice.",
  title:"Cash After the Deluge: Emergency Transfers and Post-Flood Recovery",
  rq:"Did the 2022 flood-relief cash (Rs. 25,000 via BISP to families in notified calamity areas) speed household economic recovery relative to similarly flooded but un-notified areas?",
  sub:["Recovery margins: consumption, housing repair, return migration.","Did payments reach female payees intact (deduction complaints)?","Nightlights as a village-level recovery proxy."],
  hook:"Emergency cash is now Pakistan's default disaster response. Whether it buys recovery \u2014 and how fast \u2014 determines billions in future contingency planning, yet the notification boundary that decided eligibility has barely been studied.",
  data:["geo","nser","hies","lfs"],
  ident:"Difference-in-differences exploiting the calamity-notification boundary among comparably inundated union councils (satellite-verified flood dose), with event-study dynamics on recovery outcomes; geographic RD along notification borders as a sharpening.",
  eq:"Recover_ut = \u03B1_u + \u03BB_t + \u03B2\u00B7(Notified_u \u00D7 Post_t) + \u03B4\u00B7FloodDose_u \u00D7 \u03BB_t + \u03B5_ut",
  threats:[{t:"Notification followed damage \u2014 selection on severity.",m:"Condition flexibly on satellite flood dose; compare near-boundary councils."},
   {t:"Other relief (NGOs, provincial) piled onto notified areas.",m:"Document aid flows; interpret as the notified-package effect."},
   {t:"Household outcome data thin at UC level.",m:"Nightlights + LFS pooled cells; a small phone survey if feasible."},
   {t:"Displacement complicates \u2018recovery where\u2019.",m:"Track origin- vs. destination-based outcomes explicitly."}],
  anchors:["Post-2022 flood assessments (PDNA)","Dell, Jones & Olken (2014), JEL","Nightlights-as-proxy literature (Henderson, Storeygard & Weil, AER 2012)"],
  ext:["Anticipatory cash (pre-monsoon) pilots.","Housing-reconstruction grants comparison in Sindh.","Targeting-error audit of the notification process."],flags:{}}]},
climate:{label:"Climate & Environment",sdg:"SDG 13.1, 11.5 & 3.9",
 uraan:"Environment & Climate pillar, URAAN Pakistan (5Es)",
 prov:"Provincial hooks: Sindh's post-flood reconstruction; Punjab's smog emergency plans and kiln retrofits; Living Indus initiative; National Adaptation Plan.",
 designs:[
 {id:"c1",m:"esdid",feas:"High",feasNote:"Open satellite + survey layers; a strong GIS-light thesis with big policy pull.",
  title:"Underwater: The 2022 Floods, Displacement and Work",
  rq:"How did satellite-verified flood inundation in 2022 change household migration and labor outcomes \u2014 who left, who returned, and what work absorbed them?",
  sub:["Permanent vs. temporary moves: what marks the difference?","Occupational switching out of agriculture.","Remittance responses from earlier migrants."],
  hook:"The 2022 floods displaced roughly eight million people. Whether that shock permanently rewired Pakistan's internal migration map \u2014 or snapped back \u2014 shapes urban planning, labor policy, and the next disaster's contingency design.",
  data:["geo","lfs","pslm_d","panel"],
  ident:"Event-study across districts by satellite flood dose (share of cropland inundated) on LFS/PSLM migration and employment outcomes, district and year fixed effects; within-district dose-response for sharper contrasts.",
  eq:"Y_dt = \u03B1_d + \u03BB_t + \u03A3_k \u03B2_k\u00B7Dose_d \u00D7 1[t = 2022+k] + \u03B5_dt",
  threats:[{t:"Flood dose correlates with river-adjacent poverty.",m:"District FE + pre-trend leads; compare within riverine belts."},
   {t:"Survey frames miss the displaced.",m:"Say so plainly; triangulate destination districts and nightlights."},
   {t:"Relief flows offset the shock.",m:"Interact with notification status (see the flood-cash design)."},
   {t:"One mega-event \u2014 external validity.",m:"Frame as the 2022 event's effect; compare 2010 floods with older data."}],
  anchors:["Dell, Jones & Olken (2014), JEL","Henderson, Storeygard & Weil (2012), AER \u2014 nightlights","Kirchberger and related disaster-labor literature"],
  ext:["School continuity of migrant children at destination.","Housing markets in receiving cities.","Anticipatory-migration responses to the next monsoon forecast."],flags:{}},
 {id:"c2",m:"panel",feas:"Ambitious",feasNote:"Monitor coverage is thin; the honest version is a sharp descriptive + closure event studies.",
  title:"Breathing Lessons: Smog Season, School Closures and Learning Time",
  rq:"What do Punjab's smog-emergency school closures cost in instructional time and learning \u2014 and who substitutes toward private tuition when public schooling pauses?",
  sub:["Closure incidence: which districts, how many days, since when?","Tuition-academy substitution by household wealth.","Health co-benefits: do closures measurably cut child exposure?"],
  hook:"Every November, Punjab now trades school days for air-quality days by notification. Nobody has priced that trade. Even a rigorous descriptive accounting \u2014 days lost, who substitutes, who cannot \u2014 would immediately enter the provincial policy debate.",
  data:["admin","aser","pslm_d","geo"],
  ident:"Honest panel design: a district\u00D7year dataset of notified closure days (from gazette notifications) linked to ASER learning and PSLM enrollment; event studies around the first smog-closure years; explicit refusal to over-claim causality given endogenous notification timing.",
  eq:"Learn_dt = \u03B1_d + \u03BB_t + \u03B2\u00B7ClosureDays_dt + \u03B3\u00B7AQI_dt + \u03B5_dt   (interpret \u03B2 descriptively; event-study around 2017/2021 regime changes)",
  threats:[{t:"Closures respond to the same pollution that harms learning.",m:"Separate AQI from closure-days; use notification-rule discontinuities where they exist."},
   {t:"Sparse monitor coverage.",m:"State coverage limits; satellite AOD as supplementary exposure."},
   {t:"Tuition substitution unobserved in surveys.",m:"Small primary module on academy attendance during closures."},
   {t:"Temptation to causal headline.",m:"Resist; pattern documentation + bounded claims."}],
  anchors:["Oster (2019), JBES \u2014 selection bounds","Environmental-economics evidence on pollution and cognition (e.g., Ebenstein et al.)","Punjab EPD smog action plans"],
  ext:["Kiln-retrofit rollout as a companion causal study.","Mask/air-purifier pilot in partner schools (RCT extension).","Labor-supply losses for outdoor workers on high-AQI days."],flags:{admin:true}},
 {id:"c3",m:"iv",feas:"High",feasNote:"Everything is downloadable today; the intellectual work is defending exclusion honestly.",
  title:"When the Rains Fail: Weather Shocks, Farm Income and Children's Time",
  rq:"When rainfall shocks move agricultural income, how do rural households reallocate children's time between school and work \u2014 and is the response asymmetric for droughts vs. good years?",
  sub:["Gender asymmetry in whose schooling adjusts.","Buffering: do BISP receipt or remittances mute the response?","Wage vs. own-farm channels."],
  hook:"Half of Pakistan's workforce is agricultural, exposed to increasingly erratic monsoons. Whether bad rains pull children into work \u2014 or good harvests do, via wage opportunities \u2014 flips the sign of the right policy response, as Indian evidence shows.",
  data:["geo","pslm_d","aser","panel"],
  ident:"District-season CHIRPS rainfall anomalies as an instrument/shifter for agricultural income; reduced-form and IV estimates on enrollment, attendance and child-work indicators; explicit discussion of exclusion (rain also moves disease, roads, prices) with placebo tests in non-agricultural urban samples.",
  eq:"First stage: ln(AgInc_dt) = \u03C0\u00B7RainShock_dt + \u03B1_d + \u03BB_t + \u03BD_dt ;  2SLS on School_cdt   (report AR confidence sets)",
  threats:[{t:"Exclusion violations (health, migration, prices).",m:"Placebo reduced forms in urban/non-farm samples; channel-by-channel probing; present reduced form as the headline if needed."},
   {t:"Weak first stage in irrigated belts.",m:"Interact with canal-irrigation intensity; report F and weak-IV robust CIs."},
   {t:"Anticipation via forecasts.",m:"Use realized-anomaly timing within season."},
   {t:"Measurement of child work.",m:"Combine PSLM activity questions with ASER attendance."}],
  anchors:["Shah & Steinberg (2017), Journal of Political Economy \u2014 rainfall and human capital in India","Dell, Jones & Olken (2014), JEL","Andrews, Stock & Sun (2019) \u2014 weak-IV practice"],
  ext:["Crop-insurance or anticipatory-cash moderation.","Long-run: repeated shocks and completed schooling.","Heat (not just rain) as the shifter."],flags:{}}]},
conflict:{label:"Conflict & Security",sdg:"SDG 16.1 & 4.1",
 uraan:"Equity & Empowerment pillar; peace as a development precondition",
 prov:"Provincial hooks: KP merged districts' development package; Balochistan's data-scarce security economics; National Action Plan era; two decades of GTD-recorded incidents.",
 designs:[
 {id:"k1",m:"panel",feas:"High",feasNote:"All data open; the discipline is in honest framing \u2014 which referees increasingly reward.",
  title:"Counting the Cost: District Terrorism Exposure and Human Capital",
  rq:"How do schooling and labor outcomes evolve in districts with heavy terrorism exposure \u2014 and how much of the raw gap reflects who leaves (sorting) versus what happens to those who stay (incidence)?",
  sub:["Enrollment, especially girls', around major-attack windows.","Migration sorting: composition of stayers vs. leavers.","Recovery dynamics after sustained lulls in violence."],
  hook:"Pakistan's terrorism wave was among the world's most intense, and its human-capital cost is still being tallied. Recent Labour Economics (2025) work using the 2011 bin Laden shock shows what gold-standard identification looks like here; a Master's thesis can complement it with an honest, comprehensive district panel that separates sorting from incidence.",
  data:["geo","pslm_d","lfs","census"],
  ident:"District\u00D7wave panel merging geocoded GTD/PIPS incidents with PSLM/LFS outcomes: two-way fixed effects presented as descriptive associations, event studies around the largest discrete attacks, and explicit sorting decompositions using migration modules \u2014 no causal headline the design cannot carry.",
  eq:"Y_dt = \u03B1_d + \u03BB_t + \u03B2\u00B7Attacks_d,t\u22121 + \u03B5_dt   (descriptive); event-study \u03B2_k around major incidents",
  threats:[{t:"Exposure is endogenous \u2014 militancy targets and follows local conditions.",m:"Say so on page one; event studies around plausibly unanticipated attacks; Oster bounds."},
   {t:"Survey coverage gaps in the worst periods/areas.",m:"Document coverage; nightlights as continuity check."},
   {t:"Incident-data reporting bias.",m:"GTD vs. PIPS cross-validation; robustness to casualty thresholds."},
   {t:"District boundary changes across waves.",m:"Build a careful district crosswalk once, document it, share it."}],
  anchors:["Recent Labour Economics (2025) evidence exploiting the 2011 bin Laden shock in Pakistan","Abadie & Gardeazabal (2003), AER","Bueno de Mesquita et al. \u2014 BFRS Pakistan political-violence data","Oster (2019), JBES"],
  ext:["Firm and market outcomes (electricity, nightlights) as parallel costs.","Electoral consequences of exposure.","Trust and social-cohesion outcomes where survey modules allow."],flags:{}},
 {id:"k2",m:"esdid",feas:"Medium",feasNote:"Historic exclusion of ex-FATA from surveys is the challenge \u2014 and part of the contribution.",
  title:"After the Merger: State Extension and Services in the Ex-FATA Districts",
  rq:"Did the 2018 FATA\u2013KP merger's extension of courts, police and provincial services measurably improve service delivery and dispute resolution in the merged districts?",
  sub:["Which services moved first \u2014 education, health, NADRA, courts?","Dispute resolution: formal courts vs. jirga substitution.","Returnee households' outcomes vs. never-displaced."],
  hook:"The merger ended a century-old legal carve-out for five million people \u2014 the largest state-building reform in Pakistan's recent history. Its promised \u2018mainstreaming dividend\u2019 is an explicit, budgeted policy claim that deserves measurement.",
  data:["pslm_d","mics","admin","geo"],
  ident:"Post-merger outcomes in merged districts benchmarked against adjacent settled KP districts, using the first survey rounds covering ex-FATA (PSLM 2019-20, KP MICS 2019) plus admin rollout dates of specific services; synthetic-control style comparisons where pre-period data exist at aggregate level.",
  eq:"Y_dt = \u03B1_d + \u03BB_t + \u03B2\u00B7(Merged_d \u00D7 Post2018_t) + \u03B5_dt   (with honest pre-period limitations stated)",
  threats:[{t:"Almost no pre-merger microdata for ex-FATA.",m:"Aggregate pre-series (census, EMIS, nightlights); frame partly as measured levels + convergence."},
   {t:"Security trends confound reform effects.",m:"Control incident series; discuss jointly, not separately."},
   {t:"Selective survey access within merged districts.",m:"Report enumeration coverage; sensitivity to accessible-area sample."},
   {t:"Politically sensitive interpretation.",m:"Neutral, measurement-first language; multiple-stakeholder framing."}],
  anchors:["KP government merged-areas development plans (ADP documentation)","Abadie & Gardeazabal (2003), AER \u2014 synthetic control logic","PSLM 2019-20 documentation on merged-district coverage"],
  ext:["Land formalization as records extend (link to LRMIS-style reforms).","Local government elections and accountability.","Girls' schooling as the sharpest mainstreaming test."],flags:{admin:true}}]},
governance:{label:"Governance, Law & Public Service",sdg:"SDG 16.3, 16.5 & 16.6",
 uraan:"E-Pakistan pillar, URAAN Pakistan (5Es)",
 prov:"Provincial hooks: Punjab's LRMIS land-record computerization; e-courts and case-management reforms; property-tax modernization; citizen-facing digitization as the decade's signature reform wave.",
 designs:[
 {id:"v1",m:"esdid",feas:"Medium",feasNote:"Rollout dates reconstructable; mutation/court data need letters \u2014 start month one.",
  title:"The Patwari and the Server: Land-Record Digitization and Disputes",
  rq:"Did the staggered tehsil-by-tehsil computerization of Punjab's land records (LRMIS) change transaction volumes, dispute rates, and who transacts?",
  sub:["Mutation (transfer) volumes and processing times.","Land-dispute case filings in local courts.","Distributional margin: small vs. large landholders' transactions."],
  hook:"LRMIS replaced the patwari's hand-written register with a database for tens of millions of parcels \u2014 one of the world's largest property-rights digitizations. Whether it reduced disputes and friction, or displaced rents elsewhere, is now a frontier question in the literature.",
  data:["admin","pslm_d","census"],
  ident:"Staggered difference-in-differences across tehsils by Arazi Record Center opening date (roughly 2012\u20132015), with Callaway\u2013Sant'Anna estimation on mutation volumes, processing times and dispute filings; event studies around each center's launch.",
  eq:"Y_\u03C4t = \u03B1_\u03C4 + \u03BB_t + \u03A3_k \u03B2_k\u00B71[t \u2212 Open_\u03C4 = k] + \u03B5_\u03C4t   (tehsil \u03C4, month t)",
  threats:[{t:"Rollout order followed urbanization/politics.",m:"Predict opening dates with observables; cohort event-studies; within-district tehsil contrasts."},
   {t:"Displacement: corruption or disputes may move venues, not vanish.",m:"Track multiple venues (courts, revenue offices); interpret jointly."},
   {t:"Admin data consistency pre/post digitization.",m:"Overlap-period validation; measurement-change flags."},
   {t:"Access to mutation records.",m:"PLRA letters early; published aggregates as fallback."}],
  anchors:["Beg (2022) \u2014 Pakistan land-record digitization and land/labor markets","Aman-Rana & Minaudier (2026) \u2014 digitization and corruption in Punjab land administration","Callaway & Sant'Anna (2021)"],
  ext:["Rehan (mortgage) activity as credit-market downstream effect.","Women's recorded ownership shares.","Court-case duration for land matters (link to e-courts design)."],flags:{admin:true}},
 {id:"v2",m:"esdid",feas:"Medium",feasNote:"Case-flow data via district judiciary letters; a niche with very few competitors.",
  title:"Justice, Delayed and Measured: Case-Management Reform and Court Speed",
  rq:"Did the rollout of case-management / e-filing systems across district courts reduce time-to-disposal \u2014 and did faster courts change who litigates?",
  sub:["Which case types speed up (civil, family, rent)?","Adjournment behavior by lawyers under scheduling systems.","Do faster courts pull disputes out of informal forums?"],
  hook:"Pakistan's courts hold over two million pending cases; delay is the tax everyone pays. Court-by-court reform rollouts create clean natural experiments \u2014 and Pakistan already anchors a classic in this literature (Chemin's Access to Justice evaluation).",
  data:["admin","census"],
  ident:"Stacked/staggered difference-in-differences across district courts by reform adoption date on hearing-level case-flow registers (filing \u2192 disposal), court and month fixed effects; hearing-by-hearing hazard models of case progress.",
  eq:"ln(Duration_c\u03C4) = \u03B1_\u03C4 + \u03BB_m + \u03B2\u00B7Reform_\u03C4m + \u03B5   (case c in court \u03C4, filing month m)",
  threats:[{t:"Reform courts were selected (motivated judges).",m:"Judge-transfer variation; within-judge before/after; rollout-timing prediction."},
   {t:"Composition of filings shifts with expected speed.",m:"Separate filing-volume and duration margins; new vs. backlog cases."},
   {t:"Register digitization quality varies.",m:"Sample paper-register audits for validation."},
   {t:"Access permissions.",m:"District & Sessions Judge letters with supervisor backing; anonymized extracts."}],
  anchors:["Chemin (2009), Journal of Public Economics \u2014 Pakistan's Access to Justice Programme","World Justice Project / LJCP pendency statistics","Callaway & Sant'Anna (2021)"],
  ext:["Economic downstream: contracting and credit near faster courts.","Gender: family-case duration and women litigants.","Judge-level productivity dispersion."],flags:{admin:true}},
 {id:"v3",m:"did",feas:"Ambitious",feasNote:"Best pursued with an FBR/Excise contact or as an extension of the QJE experiments' settings.",
  title:"Paying for Performance at the Property-Tax Office",
  rq:"Do incentive and posting reforms for Punjab's property-tax staff raise assessed values and collections \u2014 and at what cost in taxpayer disputes?",
  sub:["Collections vs. assessed-base growth: which margin moves?","Dispute/appeal rates as the friction cost.","Persistence after incentive windows close."],
  hook:"Khan, Khwaja & Olken's Punjab experiments made Pakistani tax administration a global reference point. Provincial excise departments keep tweaking incentive and transfer rules \u2014 each tweak is a researchable shock in a literature with a proven publication path.",
  data:["admin","census"],
  ident:"Difference-in-differences across tax circles by exposure to incentive/posting policy changes, on collections, assessed values, and appeals; where rules used cutoffs (targets), regression-discontinuity variants.",
  eq:"ln(Collections_ct) = \u03B1_c + \u03BB_t + \u03B2\u00B7Policy_ct + \u03B5_ct   (tax circle c, quarter t)",
  threats:[{t:"Circles chosen for reform differ.",m:"Pre-trend event studies; staff-rotation variation as alternative identification."},
   {t:"Gaming: reclassification instead of real base growth.",m:"Audit-style checks on property categories; dispute rates as canary."},
   {t:"Data access.",m:"Departmental MoU; published circle-level aggregates as fallback."},
   {t:"Political shocks to enforcement.",m:"Election-cycle controls."}],
  anchors:["Khan, Khwaja & Olken (2016), QJE \u2014 tax-collector performance pay","Khan, Khwaja & Olken (2019), AER \u2014 postings as incentives","Provincial Excise & Taxation reform notifications"],
  ext:["Taxpayer-facing digitization (self-assessment portals).","Spillovers to neighboring untreated circles.","Welfare accounting: revenue vs. hassle costs."],flags:{admin:true}}]},
labor:{label:"Labor, Wages & Migration",sdg:"SDG 8.5, 8.7 & 10.7",
 uraan:"Exports & Equity pillars, URAAN Pakistan (5Es) \u2014 jobs as the binding constraint",
 prov:"Provincial hooks: post-18th-Amendment provincial minimum wages; youth-employment schemes; remittances near $30bn as macro lifeline; informality above 70% of non-farm work.",
 designs:[
 {id:"l1",m:"did",feas:"High",feasNote:"LFS microdata free; provincial wage notifications public \u2014 a fast-start thesis.",
  title:"Raising the Floor: Provincial Minimum Wages and the Informal Majority",
  rq:"When provinces diverge in minimum-wage notifications, what happens to wage distributions, employment, and formality \u2014 including for the uncovered informal majority?",
  sub:["Bunching at the new minimum in formal wage distributions.","Lighthouse effects: do informal wages drift toward the announced floor?","Compliance geography: which districts' employers actually pay it?"],
  hook:"Since devolution, provinces set minimum wages separately \u2014 Sindh has repeatedly jumped ahead. Each divergence is a natural experiment on a question where Pakistani evidence is nearly empty and the informal sector makes textbook predictions unreliable.",
  data:["lfs","hies","admin"],
  ident:"Difference-in-differences across provinces around divergent notifications on LFS wage distributions; bunching estimators (Cengiz-style) around old and new minima; formal vs. informal contrasts as a built-in placebo/lighthouse test.",
  eq:"ln(w_ipt) = \u03B1_p + \u03BB_t + \u03B2\u00B7(HighMW_p \u00D7 Post_t) + X\u2032\u03B8 + \u03B5   plus bunching mass \u0394 around MW",
  threats:[{t:"Provinces differ in shocks (few clusters).",m:"Permutation inference; synthetic-control province comparisons; district-level variation in bite."},
   {t:"Wage under-reporting in LFS.",m:"Focus on distributional/bunching evidence, robust to level noise."},
   {t:"Notification \u2260 enforcement.",m:"Measure compliance directly (share below minimum) as an outcome."},
   {t:"Inflation erodes real minima quickly.",m:"Real-wage specifications; timing windows tight around notifications."}],
  anchors:["Cengiz, Dube, Lindner & Zipperer (2019), QJE \u2014 bunching approach","LFS microdata documentation (PBS)","Provincial minimum-wage-board notifications"],
  ext:["Sector carve-outs as within-province contrasts.","Firm-side response using establishment data (CMI).","Domestic-worker wage boards as a frontier case."],flags:{}},
 {id:"l2",m:"esdid",feas:"High",feasNote:"Migration modules + open shock layers; complements the climate designs neatly.",
  title:"Leaving Home to Stay Afloat: Shocks and Internal Migration",
  rq:"Which household and district characteristics turn a local shock \u2014 flood, drought, violence \u2014 into out-migration, and what do movers' outcomes look like at destination?",
  sub:["Who moves: age, education, gender composition of movers.","Destination selection: established networks vs. nearest city.","Left-behind households: remittances, women's workloads, children's schooling."],
  hook:"Internal migration is Pakistan's quiet mega-trend \u2014 far larger than international flows \u2014 yet policy treats it as an afterthought. The 2019-20 PSLM migration module plus geocoded shock layers finally make systematic analysis possible.",
  data:["pslm_d","lfs","geo","census"],
  ident:"Event-study/difference-in-differences linking district-level shock exposure (satellite floods, CHIRPS drought, GTD incidents) to migration flows from PSLM/LFS modules; origin-district fixed effects; gravity-style destination analysis as a second stage.",
  eq:"Migrate_hd,t = \u03B1_d + \u03BB_t + \u03A3_s \u03B2_s\u00B7Shock^s_d,t\u2212 + X\u2032\u03B8 + \u03B5   (shock types s entered jointly)",
  threats:[{t:"Recall error in migration timing.",m:"Coarse timing windows; cross-validate with census stock changes."},
   {t:"Origin surveys miss whole-household movers.",m:"Destination-side counts; explicitly bound the missing margin."},
   {t:"Shocks bundled (floods bring violence, price spikes).",m:"Enter shocks jointly; season-specific identification."},
   {t:"Networks unobserved.",m:"Historic migration stocks (census 1998) as network proxies."}],
  anchors:["Bryan, Chowdhury & Mobarak (2014), Econometrica \u2014 seasonal migration experiments","Henderson, Storeygard & Weil (2012), AER","PSLM 2019-20 migration module documentation"],
  ext:["Transport-subsidy pilot (RCT extension) for seasonal moves.","Urban service strain in top destination districts.","International step-migration via earlier internal moves."],flags:{}}]}
};

/* ================= PLAN, ETHICS, QUOTES ================= */
function planRows(horizon,flags){
 var brief=(horizon==="policy")||S.refine.brief;
 if(brief){return[
  {m:"Month 1",t:"Scope lock + rapid literature scan (Google Scholar alerts, PIDE/CERP/IGC repositories). One-page design memo approved by supervisor."+(flags.admin?" Data-access letters go out THIS month.":"")},
  {m:"Month 2",t:"Data acquisition: PBS microdata indent / DHS registration"+(flags.admin?" / follow up on admin letters":"")+". Ethics: departmental exempt-review filing for secondary data."},
  {m:"Month 3",t:"Cleaning + construction: district crosswalk, variable harmonization, merge keys verified twice. Descriptive tables & maps drafted."},
  {m:"Month 4",t:"Main estimation per the identification section. One meeting: show raw event-study/RD plots before polishing anything."},
  {m:"Month 5",t:"Core robustness only (the two tests your method lives on). Draft the 8-page analytical note."},
  {m:"Month 6",t:"Two-page policy brief in plain language + Urdu summary. Present to the relevant department/PIDE seminar; log feedback; archive replication files."}];}
 var rows=[
  {m:"Months 1\u20132",t:"Systematic literature review (snowball from the anchor papers; keep an annotated bibliography). Set up the replication folder from day one: version control, one master do-file, raw data never edited."+(flags.admin?" Administrative data-access letters drafted and sent with institutional signatures \u2014 the clock on these is the longest in the project.":"")},
  {m:"Month 3",t:"Proposal defense with committee. Ethics: "+(flags.primary?"FULL institutional review (ERC/IRB) application \u2014 consent forms, instruments, safeguarding protocol; budget 6\u20138 weeks.":"departmental exempt/expedited review for secondary microdata (confirm your university's rule \u2014 do not assume).")+" Register data requests: PBS microdata indent, DHS project registration."},
  {m:"Months 4\u20135",t:(flags.primary?"Instrument piloting (cognitive interviews, back-translation Urdu/regional), enumerator training, partner MoU signed; baseline fieldwork begins.":"Acquisition + raw-data audit: check every wave's questionnaire against the last; build the district/tehsil crosswalk; document every recode in a codebook memo.")},
  {m:"Month 6",t:"Construct the analysis dataset. Produce the descriptive backbone: sample sizes, outcome means, maps, and the raw treatment-control comparison BEFORE any regression."},
  {m:"Month 7",t:"Main estimation exactly as pre-specified in the identification section. First full look at the headline event-study / RD / DiD figure with your supervisor."},
  {m:"Month 8",t:"Identification diagnostics: the method's core tests (pre-trends, density, first-stage strength, balance/attrition as applicable) \u2014 these are chapters, not footnotes."},
  {m:"Month 9",t:"Robustness & heterogeneity: gender, urban/rural, province splits; alternative estimators (CS/SA vs. TWFE where relevant); specification-curve summary."},
  {m:"Month 10",t:"Write chapters: intro, background/policy, data, strategy, results. Every table has a source note and a do-file pointer."},
  {m:"Month 11",t:"Internal seminar (department / PIDE-style brownbag). Revise ruthlessly; pre-submission checklist with committee."},
  {m:"Month 12",t:"Defense submission. Dissemination: 2-page policy brief (English + Urdu) to the relevant department; working-paper version to PIDE/CERP/journal target; replication package archived."}];
 return rows;}
function ethicsText(flags){
 var t="<p>Secondary public microdata (PSLM, LFS, PDHS, ASER, MICS) is de-identified; most universities treat its analysis as exempt or expedited \u2014 but confirm with your departmental ethics committee in writing rather than assuming. Respect each dataset's terms: DHS data may not be redistributed, and the domestic-violence module carries strict handling rules.</p>";
 if(flags&&flags.admin)t+="<p><b>Administrative data:</b> obtain a written data-sharing agreement specifying permitted uses, anonymization before transfer, secure storage, and destruction/return terms. Never accept personally identified records you did not ask for.</p>";
 if(flags&&flags.primary)t+="<p><b>Primary data / experiments:</b> full institutional review (ERC/IRB) before any human contact \u2014 informed consent in the respondent's language, independent consent from women respondents, child-safeguarding protocols where minors are involved, referral pathways for any distress or disclosure, fair enumerator pay, and a commitment to report findings back to participating communities. Health-related research may additionally require National Bioethics Committee clearance. Pre-register experiments (AEA RCT Registry).</p>";
 t+="<p>Throughout: report honestly, including null results; archive a replication package; and share a plain-language summary with the officials and communities whose registers, time, and stories made the work possible.</p>";
 return t;}
var QUOTES=[
 {q:"Measure what matters to people, not only what fits in the ledger.",src:"In the spirit of Mahbub ul Haq (paraphrased)"},
 {q:"Less research ABOUT Pakistan from a distance; more research FOR Pakistan from inside it.",src:"The PIDE reform spirit (paraphrased)"},
 {q:"A good comparison group is worth a thousand adjectives.",src:"Field-kit proverb"},
 {q:"The best thesis is a finished thesis \u2014 with honest error bars.",src:"Every good supervisor, everywhere"}];
var _qi=0;function quoteHTML(){var x=QUOTES[_qi%QUOTES.length];_qi++;return '<div class="quote">\u201C'+x.q+'\u201D<span class="src">'+x.src+'</span></div>';}
var PROGRAM={education:"the girls' stipend program",health:"the Sehat Card",poverty:"BISP Kafaalat",gender:"BISP's woman-payee design",climate:"the flood-relief cash operation",conflict:"the merged-districts development package",governance:"the LRMIS computerization",labor:"the minimum-wage notification"};
var FAM={pslm_d:"survey",hies:"survey",lfs:"survey",pdhs:"survey",mics:"survey",aser:"survey",census:"survey",panel:"survey",nser:"admin",admin:"admin",geo:"geo"};
